//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WisenetBackOfficeApp.Translations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WisenetBackOfficeApp.Translations.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address is required.
        /// </summary>
        public static string BillingDataDistributorAddressRequired {
            get {
                return ResourceManager.GetString("BillingDataDistributorAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City is required.
        /// </summary>
        public static string BillingDataDistributorCityRequired {
            get {
                return ResourceManager.GetString("BillingDataDistributorCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is required.
        /// </summary>
        public static string BillingDataDistributorEmailRequired {
            get {
                return ResourceManager.GetString("BillingDataDistributorEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string BillingDataDistributorLabelAdrress {
            get {
                return ResourceManager.GetString("BillingDataDistributorLabelAdrress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string BillingDataDistributorLabelCity {
            get {
                return ResourceManager.GetString("BillingDataDistributorLabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string BillingDataDistributorLabelEmail {
            get {
                return ResourceManager.GetString("BillingDataDistributorLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tel: Movil / Phone / Fax.
        /// </summary>
        public static string BillingDataDistributorLabelMovilPhoneFax {
            get {
                return ResourceManager.GetString("BillingDataDistributorLabelMovilPhoneFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State - Country.
        /// </summary>
        public static string BillingDataDistributorLabelStateCountry {
            get {
                return ResourceManager.GetString("BillingDataDistributorLabelStateCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zip Code.
        /// </summary>
        public static string BillingDataDistributorLabelZipCode {
            get {
                return ResourceManager.GetString("BillingDataDistributorLabelZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILLING DATA.
        /// </summary>
        public static string BillingDataDistributorTitle {
            get {
                return ResourceManager.GetString("BillingDataDistributorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zip Code is required.
        /// </summary>
        public static string BillingDataDistributorZipCodeRequired {
            get {
                return ResourceManager.GetString("BillingDataDistributorZipCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string ButtonLabelLogin {
            get {
                return ResourceManager.GetString("ButtonLabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string ButtonLabelOk {
            get {
                return ResourceManager.GetString("ButtonLabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string HomeLabelId {
            get {
                return ResourceManager.GetString("HomeLabelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration Date.
        /// </summary>
        public static string HomeLabelRegistrationDate {
            get {
                return ResourceManager.GetString("HomeLabelRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sponsor.
        /// </summary>
        public static string HomeLabelSponsor {
            get {
                return ResourceManager.GetString("HomeLabelSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify your internet connection.
        /// </summary>
        public static string InternetLaberlVerifyConnection {
            get {
                return ResourceManager.GetString("InternetLaberlVerifyConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info.
        /// </summary>
        public static string LabelInfo {
            get {
                return ResourceManager.GetString("LabelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Information.
        /// </summary>
        public static string LabelUpdateData {
            get {
                return ResourceManager.GetString("LabelUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wait a moment please.
        /// </summary>
        public static string LabelWaitAMomentPlease {
            get {
                return ResourceManager.GetString("LabelWaitAMomentPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string LabelWarning {
            get {
                return ResourceManager.GetString("LabelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string LoginLabelPassword {
            get {
                return ResourceManager.GetString("LoginLabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string LoginLabelUser {
            get {
                return ResourceManager.GetString("LoginLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is required.
        /// </summary>
        public static string LoginValidateMessagePasswordRequired {
            get {
                return ResourceManager.GetString("LoginValidateMessagePasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User is required.
        /// </summary>
        public static string LoginValidateMessageUserRequired {
            get {
                return ResourceManager.GetString("LoginValidateMessageUserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Billing Data.
        /// </summary>
        public static string MenuLabelBillingData {
            get {
                return ResourceManager.GetString("MenuLabelBillingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checks.
        /// </summary>
        public static string MenuLabelChecks {
            get {
                return ResourceManager.GetString("MenuLabelChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string MenuLabelClose {
            get {
                return ResourceManager.GetString("MenuLabelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genealogy.
        /// </summary>
        public static string MenuLabelGenealogy {
            get {
                return ResourceManager.GetString("MenuLabelGenealogy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home Page.
        /// </summary>
        public static string MenuLabelHomePage {
            get {
                return ResourceManager.GetString("MenuLabelHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orders.
        /// </summary>
        public static string MenuLabelOrders {
            get {
                return ResourceManager.GetString("MenuLabelOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal Data.
        /// </summary>
        public static string MenuLabelPersonalData {
            get {
                return ResourceManager.GetString("MenuLabelPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shipping Data.
        /// </summary>
        public static string MenuLabelShippingData {
            get {
                return ResourceManager.GetString("MenuLabelShippingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount.
        /// </summary>
        public static string OrderDetailLabelAmount {
            get {
                return ResourceManager.GetString("OrderDetailLabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authorization:.
        /// </summary>
        public static string OrderDetailLabelAuthorization {
            get {
                return ResourceManager.GetString("OrderDetailLabelAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy Date.
        /// </summary>
        public static string OrderDetailLabelBuyDate {
            get {
                return ResourceManager.GetString("OrderDetailLabelBuyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cardholder Name:.
        /// </summary>
        public static string OrderDetailLabelCardHolderName {
            get {
                return ResourceManager.GetString("OrderDetailLabelCardHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commision Date.
        /// </summary>
        public static string OrderDetailLabelCommisionDate {
            get {
                return ResourceManager.GetString("OrderDetailLabelCommisionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credit Card Number:.
        /// </summary>
        public static string OrderDetailLabelCreditCardNumber {
            get {
                return ResourceManager.GetString("OrderDetailLabelCreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expiration Date:.
        /// </summary>
        public static string OrderDetailLabelExpirationDate {
            get {
                return ResourceManager.GetString("OrderDetailLabelExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FastStart.
        /// </summary>
        public static string OrderDetailLabelFastStart {
            get {
                return ResourceManager.GetString("OrderDetailLabelFastStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ORDER ID.
        /// </summary>
        public static string OrderDetailLabelOrder {
            get {
                return ResourceManager.GetString("OrderDetailLabelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order Type.
        /// </summary>
        public static string OrderDetailLabelOrderType {
            get {
                return ResourceManager.GetString("OrderDetailLabelOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Form:.
        /// </summary>
        public static string OrderDetailLabelPaymentForm {
            get {
                return ResourceManager.GetString("OrderDetailLabelPaymentForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Reference:.
        /// </summary>
        public static string OrderDetailLabelPaymentReference {
            get {
                return ResourceManager.GetString("OrderDetailLabelPaymentReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Points.
        /// </summary>
        public static string OrderDetailLabelPoints {
            get {
                return ResourceManager.GetString("OrderDetailLabelPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shipping And Handling.
        /// </summary>
        public static string OrderDetailLabelShippingAndHandling {
            get {
                return ResourceManager.GetString("OrderDetailLabelShippingAndHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ship To.
        /// </summary>
        public static string OrderDetailLabelShipTo {
            get {
                return ResourceManager.GetString("OrderDetailLabelShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address:.
        /// </summary>
        public static string OrderDetailLabelShipToAddress {
            get {
                return ResourceManager.GetString("OrderDetailLabelShipToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        public static string OrderDetailLabelShipToName {
            get {
                return ResourceManager.GetString("OrderDetailLabelShipToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order Date:.
        /// </summary>
        public static string OrderDetailLabelShipToOrderDate {
            get {
                return ResourceManager.GetString("OrderDetailLabelShipToOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shipping Method:.
        /// </summary>
        public static string OrderDetailLabelShipToShippingMethod {
            get {
                return ResourceManager.GetString("OrderDetailLabelShipToShippingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Name:.
        /// </summary>
        public static string OrderDetailLabelShipToUserName {
            get {
                return ResourceManager.GetString("OrderDetailLabelShipToUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warehouse:.
        /// </summary>
        public static string OrderDetailLabelShipToWarehouse {
            get {
                return ResourceManager.GetString("OrderDetailLabelShipToWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sold To.
        /// </summary>
        public static string OrderDetailLabelSoldTo {
            get {
                return ResourceManager.GetString("OrderDetailLabelSoldTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address:.
        /// </summary>
        public static string OrderDetailLabelSoldToAddress {
            get {
                return ResourceManager.GetString("OrderDetailLabelSoldToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        public static string OrderDetailLabelSoldToName {
            get {
                return ResourceManager.GetString("OrderDetailLabelSoldToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SubTotal.
        /// </summary>
        public static string OrderDetailLabelSubtotal {
            get {
                return ResourceManager.GetString("OrderDetailLabelSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax.
        /// </summary>
        public static string OrderDetailLabelTax {
            get {
                return ResourceManager.GetString("OrderDetailLabelTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string OrderDetailLabelTotal {
            get {
                return ResourceManager.GetString("OrderDetailLabelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume.
        /// </summary>
        public static string OrderDetailLabelVolume {
            get {
                return ResourceManager.GetString("OrderDetailLabelVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orders.
        /// </summary>
        public static string OrdersLabelTitle {
            get {
                return ResourceManager.GetString("OrdersLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birthdate is required.
        /// </summary>
        public static string PersonalDataDistributorBirthDateRequired {
            get {
                return ResourceManager.GetString("PersonalDataDistributorBirthDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birthdate has been updated.
        /// </summary>
        public static string PersonalDataDistributorBirthDateUpdated {
            get {
                return ResourceManager.GetString("PersonalDataDistributorBirthDateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BirhtDate.
        /// </summary>
        public static string PersonalDataDistributorLabelBirthDate {
            get {
                return ResourceManager.GetString("PersonalDataDistributorLabelBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company Name.
        /// </summary>
        public static string PersonalDataDistributorLabelCompanyName {
            get {
                return ResourceManager.GetString("PersonalDataDistributorLabelCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscription Date.
        /// </summary>
        public static string PersonalDataDistributorLabelInscriptionDate {
            get {
                return ResourceManager.GetString("PersonalDataDistributorLabelInscriptionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distributor Package.
        /// </summary>
        public static string PersonalDataDistributorLabelPackage {
            get {
                return ResourceManager.GetString("PersonalDataDistributorLabelPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sponsor.
        /// </summary>
        public static string PersonalDataDistributorLabelSponsor {
            get {
                return ResourceManager.GetString("PersonalDataDistributorLabelSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PERSONAL DATA.
        /// </summary>
        public static string PersonalDataDistributorTitle {
            get {
                return ResourceManager.GetString("PersonalDataDistributorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string ShippingDataDistributorLabelAddress {
            get {
                return ResourceManager.GetString("ShippingDataDistributorLabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string ShippingDataDistributorLabelCity {
            get {
                return ResourceManager.GetString("ShippingDataDistributorLabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        public static string ShippingDataDistributorLabelCountry {
            get {
                return ResourceManager.GetString("ShippingDataDistributorLabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string ShippingDataDistributorLabelEmail {
            get {
                return ResourceManager.GetString("ShippingDataDistributorLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fax.
        /// </summary>
        public static string ShippingDataDistributorLabelFax {
            get {
                return ResourceManager.GetString("ShippingDataDistributorLabelFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Names.
        /// </summary>
        public static string ShippingDataDistributorLabelLastNames {
            get {
                return ResourceManager.GetString("ShippingDataDistributorLabelLastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movil.
        /// </summary>
        public static string ShippingDataDistributorLabelMovil {
            get {
                return ResourceManager.GetString("ShippingDataDistributorLabelMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Names.
        /// </summary>
        public static string ShippingDataDistributorLabelNames {
            get {
                return ResourceManager.GetString("ShippingDataDistributorLabelNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string ShippingDataDistributorLabelPhone {
            get {
                return ResourceManager.GetString("ShippingDataDistributorLabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        public static string ShippingDataDistributorLabelState {
            get {
                return ResourceManager.GetString("ShippingDataDistributorLabelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zip Code.
        /// </summary>
        public static string ShippingDataDistributorLabelZipCode {
            get {
                return ResourceManager.GetString("ShippingDataDistributorLabelZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string ShippingInformationLabelAdrress {
            get {
                return ResourceManager.GetString("ShippingInformationLabelAdrress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string ShippingInformationLabelCity {
            get {
                return ResourceManager.GetString("ShippingInformationLabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string ShippingInformationLabelEmail {
            get {
                return ResourceManager.GetString("ShippingInformationLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        public static string ShippingInformationLabelLastName {
            get {
                return ResourceManager.GetString("ShippingInformationLabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string ShippingInformationLabelName {
            get {
                return ResourceManager.GetString("ShippingInformationLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movil / Phone / Fax.
        /// </summary>
        public static string ShippingInformationLabelPhone {
            get {
                return ResourceManager.GetString("ShippingInformationLabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State - Country.
        /// </summary>
        public static string ShippingInformationLabelStateCountry {
            get {
                return ResourceManager.GetString("ShippingInformationLabelStateCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SHIPPING INFORMATION.
        /// </summary>
        public static string ShippingInformationTitle {
            get {
                return ResourceManager.GetString("ShippingInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check your internet connection or try again.
        /// </summary>
        public static string WebserviceLabelTimeOut {
            get {
                return ResourceManager.GetString("WebserviceLabelTimeOut", resourceCulture);
            }
        }
    }
}
